npmScopes:
  fxd-dev-util:
    npmRegistryServer: "https://git.fxdigital.uk/api/v4/packages/npm/"
  fxd-ott:
    npmRegistryServer: "https://git.fxdigital.uk/api/v4/packages/npm/"

packageExtensions:
  "@nestjs/core@*":
    peerDependencies:
      class-transformer: "*"
      class-validator: "*"
    peerDependenciesMeta:
      "@nestjs/platform-express":
        optional: true
      class-transformer:
        optional: true
      class-validator:
        optional: true

yarnPath: .yarn/releases/yarn-2.4.2.cjs
